### ISSUE TITLE
[Regression] Lintdiff is not detecting tags changed or files changed, but running on default readme tag

### ISSUE THREAD

**Issue by veronicagg** [Azure/rest-api-specs-scripts#8]
Moment of truth script had logic to detect which tags were affected by changes and/or which individual files were updated, so linter would run on the changes.
At the moment, as seen in https://dev.azure.com/azure-sdk/public/_build/results?buildId=25525&view=logs&jobId=688669d0-441c-57c3-cf6d-f89a22ccfa5d&taskId=923b5a90-e462-5994-c166-86509c6bf5f2&lineStart=33&lineEnd=34&colStart=1&colEnd=1 lintdiff executed on the default tag, though it should have been executing on the tag that was updated based on the file changes. Because of this the linter results are not actually relevant for the PR and issues can be missed.

**Comment by jianyexi** [comment]
Resolved since 0.9.0
